//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy.Database.SQLQuery.Product {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Legacy.Database.SQLQuery.Product.ProductQuery", typeof(ProductQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from  [dbo].[POC_BFI_Product]  where ProductId = @ProductId
        ///.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @sql varchar(max) = &apos;&apos;;
        ///set @sql = &apos;select
        ///	ProductId,
        ///	ProductName,
        ///	Description,
        ///	Price,
        ///	ExpiredDate
        ///from  [dbo].[POC_BFI_Product]
        ///	where @SearchByText like @SearchByValue
        ///ORDER BY @OrderBy asc
        ///OFFSET (@Page-1)*@Size ROWS
        ///FETCH NEXT @Size ROWS ONLY&apos;
        ///
        ///	if	isnull(@SearchByText,&apos;&apos;) = &apos;&apos; or isnull(@SearchByValue,&apos;&apos;)=&apos;&apos;
        ///		begin set @sql = REPLACE(@sql,&apos;where @SearchByText like @SearchByValue&apos;,&apos;&apos;) end
        ///	
        ///	set @sql = REPLACE(@sql,&apos;@SearchByText&apos;,@SearchByText)
        ///	set @sql = REPLACE(@sql,&apos;@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetData {
            get {
                return ResourceManager.GetString("GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into  [dbo].[POC_BFI_Product]
        ///(
        ///ProductId,
        ///ProductName,
        ///Description,
        ///Price,
        ///ExpiredDate)
        ///values
        ///(
        ///@ProductId,
        ///@ProductName,
        ///@Description,
        ///@Price,
        ///@ExpiredDate)
        ///.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update [dbo].[POC_BFI_Product] set
        ///ProductName = @ProductName,
        ///Description = @Description,
        ///Price = @Price,
        ///ExpiredDate = @ExpiredDate
        ///where ProductId = @ProductId
        ///
        ///.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
